[build]
  command = "cd client && npm run build"
  publish = "client/build"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 5000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200